version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/project/simetrik/dockerhub-username"
    DOCKERHUB_PASSWORD: "/project/simetrik/dockerhub-password"
    FRONTEND_IMAGE: "/project/simetrik/frontend-image"
    BACKEND_IMAGE:  "/project/simetrik/backend-image"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Start building Client.py"
      - pylint client/client.py
      - COMMIT_SHA=$(git rev-parse HEAD)
      - DOCKER_TAG=$(echo $COMMIT_SHA | cut -c1-7)
      - docker build -t $FRONTEND_IMAGE -t $FRONTEND_IMAGE:$DOCKER_TAG client/.
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker push $FRONTEND_IMAGE
      - docker push $FRONTEND_IMAGE:$DOCKER_TAG
      - echo "Start building Server.py"
      - pylint server/server.py
      - docker build -t $BACKEND_IMAGE -t $BACKEND_IMAGE:$DOCKER_TAG server/.
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker push $BACKEND_IMAGE
      - docker push $BACKEND_IMAGE:$DOCKER_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
