version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/project/simetrik/dockerhub-username"
    DOCKERHUB_PASSWORD: "/project/simetrik/dockerhub-password"
    FRONTEND_IMAGE: "/project/simetrik/frontend-image"
    BACKEND_IMAGE:  "/project/simetrik/backend-image"
    CLUSTER_NAME:  "/project/simetrik/cluster-name"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod +x get_helm.sh
      - ./get_helm.sh
      - helm version

  build:
    commands:
      - echo "Start building Client.py"
      - pylint client/client.py
      - COMMIT_SHA=$(git rev-parse HEAD)
      - DOCKER_TAG=$(echo $COMMIT_SHA | cut -c1-7)
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker build -t $FRONTEND_IMAGE -t $FRONTEND_IMAGE:$DOCKER_TAG -f client/Dockerfile.client client/.
      - docker push $FRONTEND_IMAGE
      - docker push $FRONTEND_IMAGE:$DOCKER_TAG
      - echo "Start building Server.py"
      - pylint server/server.py
      - docker build -t $BACKEND_IMAGE -t $BACKEND_IMAGE:$DOCKER_TAG -f server/Dockerfile.server server/.
      - docker push $BACKEND_IMAGE
      - docker push $BACKEND_IMAGE:$DOCKER_TAG
      - aws eks --region us-east-1 update-kubeconfig --name $CLUSTER_NAME

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Start deployment"
      - helm upgrade --install python-app -f helm/values.yaml --set frontend.image=$FRONTEND_IMAGE:$DOCKER_TAG --set backend.image=$BACKEND_IMAGE:$DOCKER_TAG helm/.
      - echo "Deployment completed on $(date)"

