version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/project/simetrik/dockerhub-username"
    DOCKERHUB_PASSWORD: "/project/simetrik/dockerhub-password"
    FRONTEND_IMAGE: "/project/simetrik/frontend-image"
    BACKEND_IMAGE:  "/project/simetrik/backend-image"
    CLUSTER_NAME:  "/project/simetrik/cluster-name"
    GITHUB_TOKEN: "/project/simetrik/github-token"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - chmod +x update_image_tag.sh

  build:
    commands:
      - echo "Start building Client.py"
      - pylint client/client.py
      - COMMIT_SHA=$(git rev-parse HEAD)
      - DOCKER_TAG=$(echo $COMMIT_SHA | cut -c1-7)
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker build -t $FRONTEND_IMAGE -t $FRONTEND_IMAGE:$DOCKER_TAG -f client/Dockerfile.client client/.
      - docker push $FRONTEND_IMAGE
      - docker push $FRONTEND_IMAGE:$DOCKER_TAG
      - echo "Start building Server.py"
      - pylint server/server.py
      - docker build -t $BACKEND_IMAGE -t $BACKEND_IMAGE:$DOCKER_TAG -f server/Dockerfile.server server/.
      - docker push $BACKEND_IMAGE
      - docker push $BACKEND_IMAGE:$DOCKER_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Updating the image tag"
      - bash update_image_tag.sh $DOCKER_TAG
      - echo "Updating the repo"
      - git config --global user.email "codebuild@example.com"
      - git config --global user.name "CodeBuild"
      - git add helm/values.yml
      - git commit -m "Update image tag to $IMAGE_TAG"
      - git tag -a $IMAGE_TAG -m "Release $IMAGE_TAG"
      - git remote set-url origin https://$GITHUB_TOKEN@github.com/rancesking/Challenge-sm.git
      - git push origin main
      - echo "CD completed on $(date)"


