# Dockerfile.server

FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY communication.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. communication.proto

CMD ["python", "server.py"]